### ISSUE TITLE
enforce single-assignee per issue/PR

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#110] opened 2016-08-27 09:38 UTC
## requirements
We are trying to avoid using multiple assignees per issue/PR. In fact, having an issue with multiple assignees is almost always a sign that the issue should become a macro issue with multiple sub-issues assigned to a single person.

@nemobot should forbid multiple assignees and, if possible, should automatically select the last assigned and remove the other so we can do again:
- "a"
- search for assignee name
- select new assignee
- "esc"
- @nemobot removes old assignee(s) automatically in a matter of micro-seconds

## specs
in the UI the `assignees` is a list ordered by added-date.
I expect the field `assignees` returned by GitHub API to be an array also ordered by added-date where the newest assignee is the last value of the array.
**verify this accurately**

If this is true @nemobot should:
- listen to issue/PR "assigned" action
- is there multiple assignees?
  - remove every assignee **but** last one from issue/PR

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment] 2016-08-27 09:43
@lucacioria @gabro @buildo/everyone 
Do you agree with this?

If you're wondering about who should be the assignee of a macro issue I haven't got an answer but I can say:
- at buildo the assignee of an issue is the dev that will implement/fix the issue by opening a PR.
- macro issues are **non-executive** and should never have a PR: why should it have an assignee?
- macro issue status is usually more useful for PMs than devs.

@lucacioria any additional (and more precise) thoughts?

**Comment by lucacioria** [comment] 2016-08-29 15:02
I would say there are 3 scenarios:
- sub-issues all have the same assignee => macro can have the same assignee
- sub-issues have different assignees:
  - one main one (owner of the macro issue) and minor ones => macro should have the owner as assignee so that PM and others clearly know who to talk to
  - most devs at the same level, as the issue is very horizontal => not sure.. I would either have it unassigned (it's clear there is no owner, and this might be a problem or not) or define an owner and assign it (the assignee is the owner as usual, no confusion)

In any case, i don't see any value in multiple assignees except to see who works on it, which can be easily seen from the sub-issues chapter at the moment.

My opinion is therefore to leave it manual and enforce max 1 assignee per issue, but not enforce a macro issue to have an assignee.

**Closed** 2016-09-02 09:26 UTC
Labels: in review
